// Mapeia o prefixo do código da figurinha (e o nome do grupo) para o emoji de bandeira.
// Os códigos seguem o padrão FIFA, que diverge do ISO-3166 em vários casos
// (ex: ENG = Inglaterra, RSA = África do Sul, KSA = Arábia Saudita, SCO = Escócia),
// por isso o mapeamento é manual em vez de gerado automaticamente a partir da sigla.
export const BANDEIRAS_POR_NOME: Record<string, string> = {
  'México': '🇲🇽',
  'África do Sul': '🇿🇦',
  'Coreia do Sul': '🇰🇷',
  'Rep. Tcheca': '🇨🇿',
  'Canadá': '🇨🇦',
  'Bósnia': '🇧🇦',
  'Catar': '🇶🇦',
  'Suíça': '🇨🇭',
  'Brasil': '🇧🇷',
  'Marrocos': '🇲🇦',
  'Haiti': '🇭🇹',
  'Escócia': '🏴',
  'Estados Unidos': '🇺🇸',
  'Paraguai': '🇵🇾',
  'Austrália': '🇦🇺',
  'Turquia': '🇹🇷',
  'Alemanha': '🇩🇪',
  'Curaçao': '🇨🇼',
  'Costa do Marfim': '🇨🇮',
  'Equador': '🇪🇨',
  'Holanda': '🇳🇱',
  'Japão': '🇯🇵',
  'Suécia': '🇸🇪',
  'Tunísia': '🇹🇳',
  'Bélgica': '🇧🇪',
  'Egito': '🇪🇬',
  'Irã': '🇮🇷',
  'Nova Zelândia': '🇳🇿',
  'Espanha': '🇪🇸',
  'Cabo Verde': '🇨🇻',
  'Arábia Saudita': '🇸🇦',
  'Uruguai': '🇺🇾',
  'França': '🇫🇷',
  'Senegal': '🇸🇳',
  'Iraque': '🇮🇶',
  'Noruega': '🇳🇴',
  'Argentina': '🇦🇷',
  'Argélia': '🇩🇿',
  'Áustria': '🇦🇹',
  'Inglaterra': '🏴',
  'Colômbia': '🇨🇴',
  'Croácia': '🇭🇷',
  'Gana': '🇬🇭',
  'Jordânia': '🇯🇴',
  'Panamá': '🇵🇦',
  'Portugal': '🇵🇹',
  'Congo': '🇨🇩',
  'Uzbequistão': '🇺🇿',
  'Fifa World Cup': '🏆',
  'Coca-Cola': '🥤',
};

export function bandeiraDoGrupo(nomeGrupo: string): string {
  return BANDEIRAS_POR_NOME[nomeGrupo] ?? '📌';
}
